kind: pipeline
name: default

steps:
- name: backend
  image: golang
  commands:
  - go build
  - go test
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: dh_user
    password:
      from_secret: dh_pass
    repo: allanmatheus/testing-cd
    tags: latest
